name: Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/nodemaster
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Fail if Snyk found high vulnerabilities
        run: |
          if [[ -n "$(grep 'high severity vulnerabilities found' snyk-report.json)" ]]; then
            echo "High vulnerabilities found. Exiting."
            exit 1
          fi

